import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useRouter } from "next/router";

export const metadata: Metadata = {
  title: "Home - IoTani",
  description: "Generated by create next app",
};

const disableNavigation = ["/auth/login", "/auth/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { pathname } = useRouter();
  const showNavigation = !disableNavigation.includes(pathname);
  return (
    <html lang="en">
      <body className={"antialiased"}>
        {showNavigation && <Navbar />}
        {children}
        {showNavigation && <Footer />}
      </body>
    </html>
  );
}
